mod bitboard;
pub mod board;
mod castle_rights;
mod computed_boards;
mod r#const;
pub mod engine;
mod fen_parser;
mod game_state;
pub mod magic_tables;
mod make_move;
mod masks;
pub mod r#move;
mod move_generation;
mod piece;
pub mod position;
pub mod utils;
mod zobrist;
