pub mod board; 
pub mod position;
pub mod r#move;
pub mod magic_tables;
pub mod utils;
mod game_state;
mod computed_boards;
mod castle_rights;
mod piece;
mod move_generation;
mod bitboard;
mod masks;
mod fen_parser;
mod r#const;
mod zobrist;
mod make_move;